seed: 1414
data_path: ./
train_batch_size: 32
eval_batch_size: 32
num_workers: 4
max_epochs: 1
train_epoch_length: 100
eval_epoch_length: 100
lr: 0.0001
use_amp: false
debug: false
model: resnet18
filename_prefix: training
n_saved: 2
save_every_iters: 100
patience: 3
output_dir: ./logs
log_every_iters: 2
