seed: 1414
dataset: coco
data_path: ./
train_path: /mnt/data/coco/train2017
validation_path: /mnt/data/coco/val2017
train_ann_path: /mnt/data/coco/annotations_trainval2017/annotations/instances_train2017.json
validation_ann_path: /mnt/data/coco/annotations_trainval2017/annotations/instances_val2017.json
train_batch_size: 2
eval_batch_size: 2
num_workers: 4
max_epochs: 1
train_epoch_length: 100
eval_epoch_length: 100
lr: 0.0001
use_amp: false
debug: false
model: resnet18
filename_prefix: training
n_saved: 2
save_every_iters: 100
patience: 3
output_dir: ./logs
log_every_iters: 2
