name: torch-demo
channels:
  - conda-forge
dependencies:
  - ipykernel
  - ipywidgets
  - matplotlib
  - pip
  - pre-commit
  - python
  - pytorch
  - pytorch-gpu
  - pyyaml
  - tensorboard
  - torchvision
  - pip:
      - python-dotenv
      - pytorch-ignite
      - torch_tb_profiler
