name: torch-demo
# set CONDA_OVERRIDE_CUDA=11.8
channels:
- conda-forge
- nvidia
dependencies:
- ipykernel
- ipywidgets
- matplotlib
- numpy
- pre-commit
- python
- pytorch-gpu>=1.13.1
- pyyaml
- tensorboard
- torchvision
- python-dotenv
- pytorch-ignite
- pip:
  - torch_tb_profiler
