name: tiny-torch
channels:
  - conda-forge
dependencies:
  - cudatoolkit
  - ipykernel
  - matplotlib
  - numpy
  - pre-commit
  - pytest
  - pytest-cov
  - python
  - pytorch
  - tensorboard
  - tqdm
