name: ignite-env
channels:
  - conda-forge
dependencies:
  - ipykernel
  - matplotlib
  - pre-commit
  - python
  - pytorch>=1.10.2
  - pytorch-ignite>=0.4.8
  - pyyaml
  - tensorboard
  - torchvision>=0.11.3
