kind: Workflow
metadata:
  generateName: train-eval-vis
spec:
  entrypoint: pipeline
  templates:
  - name: pipeline
    dag:
      tasks:
        - name: main
          template: main-template
        - name: evaluate
          template: evaluate-template
          dependencies: [train]
          arguments:
            artifacts:
              - name: model
                from: "{{tasks.main.outputs.artifacts.model-pt}}"
        - name: visualize
          template: visualize-template
          dependencies: [train]
          arguments:
            artifacts:
              - name: model
                from: "{{tasks.train.outputs.artifacts.model-pt}}"
