kind: Workflow
metadata:
  generateName: train-eval-vis
spec:
  entrypoint: pipeline
  templates:
  - name: pipeline
    dag:
      tasks:
        - name: main
          template: main-template
#        - name: evaluate
#          template: evaluate-template
#          dependencies:
#            - main
#          arguments:
#            artifacts:
#              - name: model
#                from: '{{tasks.main.outputs.artifacts.model-pt}}'
#        - name: visualize
#          template: visualize-template
#          dependencies:
#            - main
#          arguments:
#            artifacts:
#              - name: model
#                from: '{{tasks.main.outputs.artifacts.model-pt}}'
  - name: main-template
    container:
      image: ericdatakelly/nebari-workflow2
      command: ['python', 'main.py']
    outputs:
      artifacts:
        - name: model-pt
          path: output/model.pt
#  - name: evaluate-template
#    container:
#      image: ericdatakelly/nebari-workflow2
#      command: ['python', 'evaluate.py']
#  - name: visualize-template
#    container:
#      image: ericdatakelly/nebari-workflow2
#      command: ['python', 'visualize.py' ]
