seed: 1414
output_dir: ./logs
log_every_iters: 5
debug: false
use_amp: false

# Dataflow
data_path: ./
train_batch_size: 512
eval_batch_size: 1024
num_workers: 4

# Model
model: resnet152

# Training
max_epochs: 15
optimizer: Adam
lr: 0.001
filename_prefix: training
n_saved: 2
save_every_iters: 100
patience: 3

